/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROVEEDOR_H_RPCGEN
#define _PROVEEDOR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define PROVEEDOR_PROG ((rpc_uint)0x20000001)
#define PROVEEDOR_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define IMPRIMIR_INVENTARIO ((rpc_uint)1)
extern "C" int * imprimir_inventario_1(void *, CLIENT *);
extern "C" int * imprimir_inventario_1_svc(void *, struct svc_req *);
#define INICIALIZAR_TABLA_PRODUCTOS ((rpc_uint)2)
extern "C" int * inicializar_tabla_productos_1(void *, CLIENT *);
extern "C" int * inicializar_tabla_productos_1_svc(void *, struct svc_req *);
#define ACTUALIZAR_INVENTARIO ((rpc_uint)3)
extern "C" int * actualizar_inventario_1(void *, CLIENT *);
extern "C" int * actualizar_inventario_1_svc(void *, struct svc_req *);
#define CONSULTAR_INVENTARIO ((rpc_uint)4)
extern "C" char ** consultar_inventario_1(char **, CLIENT *);
extern "C" char ** consultar_inventario_1_svc(char **, struct svc_req *);
#define REALIZAR_PEDIDO ((rpc_uint)5)
extern "C" char ** realizar_pedido_1(char **, CLIENT *);
extern "C" char ** realizar_pedido_1_svc(char **, struct svc_req *);

#elif __STDC__
#define IMPRIMIR_INVENTARIO ((rpc_uint)1)
extern  int * imprimir_inventario_1(void *, CLIENT *);
extern  int * imprimir_inventario_1_svc(void *, struct svc_req *);
#define INICIALIZAR_TABLA_PRODUCTOS ((rpc_uint)2)
extern  int * inicializar_tabla_productos_1(void *, CLIENT *);
extern  int * inicializar_tabla_productos_1_svc(void *, struct svc_req *);
#define ACTUALIZAR_INVENTARIO ((rpc_uint)3)
extern  int * actualizar_inventario_1(void *, CLIENT *);
extern  int * actualizar_inventario_1_svc(void *, struct svc_req *);
#define CONSULTAR_INVENTARIO ((rpc_uint)4)
extern  char ** consultar_inventario_1(char **, CLIENT *);
extern  char ** consultar_inventario_1_svc(char **, struct svc_req *);
#define REALIZAR_PEDIDO ((rpc_uint)5)
extern  char ** realizar_pedido_1(char **, CLIENT *);
extern  char ** realizar_pedido_1_svc(char **, struct svc_req *);

#else /* Old Style C */
#define IMPRIMIR_INVENTARIO ((rpc_uint)1)
extern  int * imprimir_inventario_1();
extern  int * imprimir_inventario_1_svc();
#define INICIALIZAR_TABLA_PRODUCTOS ((rpc_uint)2)
extern  int * inicializar_tabla_productos_1();
extern  int * inicializar_tabla_productos_1_svc();
#define ACTUALIZAR_INVENTARIO ((rpc_uint)3)
extern  int * actualizar_inventario_1();
extern  int * actualizar_inventario_1_svc();
#define CONSULTAR_INVENTARIO ((rpc_uint)4)
extern  char ** consultar_inventario_1();
extern  char ** consultar_inventario_1_svc();
#define REALIZAR_PEDIDO ((rpc_uint)5)
extern  char ** realizar_pedido_1();
extern  char ** realizar_pedido_1_svc();
#endif /* Old Style C */

#endif /* !_PROVEEDOR_H_RPCGEN */
